[package]
name = "fish_history_abbreviation"
description = "something"
version = "0.1.0"
edition = "2024"
categories = ["fish"]
license = "GPLv3+"
readme = "README.md"
keywords = ["fish"]
repository = "git.gay/nicole/fish-history-abbreviation"

[dependencies]
